version: "3.7"
services:
  main-api:
    container_name: main-api
    restart: always
    build: ./
    environment:
      DATABASE_HOST: mongodb://mongo
      DATABASE_NAME: language_of_film
      JWT_SECRET: gkjh2314j3jk4
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    command: yarn dev
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: --quiet